import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { useStore } from '../store/useStore.js'
import { useUI } from '../store/useUI.js'
import { uid, DAYN } from '../lib/format.js'
import { t } from '../lib/i18n.js'
import { FOODS } from '../lib/foods-data.js'
import { GOALS } from '../lib/training-plans.js'
import { DEFAULT_NUTRITION_PROFILE, DIETS, ALLERGENS, INTOLERANCES, CULTURAL, generateNutritionPlan, eligibleMeals, swapMeal, dayNutrients, entryNutrients, estimateRange, groceryList, checkNutritionPlan, saveNutritionPreferences, activateNutritionPlan } from '../lib/nutrition-plans.js'
import { Field, Select, Check, Choices, ErrorNotice } from '../components/PlannerFields.jsx'

const clone = x => JSON.parse(JSON.stringify(x))
const mealLabels = ['Breakfast', 'Lunch', 'Dinner', 'Snack', 'Second snack']
export default function Nutrition() {
  const nav = useNavigate(), S = useStore(s => s.S), update = useStore(s => s.update)
  const [p, setP] = useState({ ...DEFAULT_NUTRITION_PROFILE, ...(S.plannerProfile?.nutrition || {}) })
  const [mode, setMode] = useState('build'), [preview, setPreview] = useState(null), [dayIndex, setDayIndex] = useState(0)
  const showingPreview = !!preview
  useEffect(() => { window.scrollTo(0, 0) }, [mode, showingPreview])
  const [error, setError] = useState(''), [query, setQuery] = useState('')
  const act = fn => { try { fn(); setError('') } catch (e) { setError(e.message) } }
  const change = (key, value) => { setP(x => ({ ...x, [key]: value, ...(key === 'exclusionsConfirmed' ? {} : { exclusionsConfirmed: false }) })); setError('') }
  const notify = message => useUI.getState().toast(t(message))
  const save = () => act(() => {
    const issue = checkNutritionPlan(preview, p)
    if (issue) throw new Error(issue)
    update(s => { saveNutritionPreferences(s, p); s.dietPlans.push({ ...clone(preview), id: uid(), createdAt: Date.now() }) })
    setPreview(null); setMode('saved'); notify('Meal plan saved. Activate it when ready.')
  })
  const activate = id => act(() => { update(s => { saveNutritionPreferences(s, p); activateNutritionPlan(s, id) }); notify('Meal plan activated.') })
  const shownFoods = FOODS.filter(f => f.name.toLowerCase().includes(query.toLowerCase()))
  const day = preview?.days[dayIndex], totals = day && dayNutrients(day)
  const activeDiet = S.dietPlans?.find(d => d.id === S.activeDietPlanId)
  const scheduleChanged = activeDiet && JSON.stringify(activeDiet.scheduleSnapshot) !== JSON.stringify(S.week)
  return <div className="planner-page">
    <div className="hdr"><div><h1>{t('Meals & nutrition')}</h1><div className="sub">{t('Everyday Indian meals, built around you.')}</div></div><button className="btn ghost" onClick={() => preview ? setPreview(null) : nav('/home')}>{t('Back')}</button></div>
    <ErrorNotice error={error} />
    {preview ? <>
      <section className="planner-hero"><span className="tag acc">{t('7-day preview')}</span><Field label="Plan name"><input className="input" maxLength={100} value={preview.name} onChange={e => setPreview(x => ({ ...x, name: e.target.value }))} /></Field><p>{preview.target ? `${t('Estimated daily energy range')}: ${preview.target.low}–${preview.target.high} kcal. ${preview.target.method}` : t('A portion-based sample menu, not a personal calorie prescription. Adjust portions to your appetite and needs; this is not a guarantee of nutritional completeness.')}</p><p className="small">{t('Workout days favor a carbohydrate-containing snack when available. You can eat it at a comfortable time around training; it is a swap, not extra food added on top.')}</p><ErrorNotice error={checkNutritionPlan(preview, p)} /></section>
      <div className="planner-tabs" aria-label={t('Menu days')}>{preview.days.map((d, i) => <button key={d.weekday} className={'btn ' + (i === dayIndex ? 'primary' : 'ghost')} aria-pressed={i === dayIndex} onClick={() => setDayIndex(i)}>{t(DAYN[d.weekday])}{d.training ? ' •' : ''}</button>)}</div>
      <div className="row between"><h2>{t(DAYN[day.weekday])} · {t(day.training ? 'Workout day' : 'Rest day')}</h2></div>
      <p className="small muted">~{estimateRange(totals.kcal, 10)} kcal · ~{estimateRange(totals.protein)} g {t('protein')} · ~{estimateRange(totals.fiber)} g {t('fiber')}. {t('Ranges reflect ordinary ingredient and preparation variation, not measured accuracy.')}</p>
      <div className="planner-grid">{day.entries.map((e, i) => {
        const n = entryNutrients(e)
        return <article className="card" key={i}><span className="tag">{t(mealLabels[i])}</span><h2>{t(e.recipe.name)}</h2><p className="small muted">{e.scale}× {t('recipe portion')} · ~{estimateRange(n.kcal, 10)} kcal · ~{estimateRange(n.protein)} g {t('protein')}</p>
          <Select label={`Swap ${mealLabels[i]}`} value={e.mealId} onChange={id => act(() => setPreview(swapMeal(preview, dayIndex, i, id, p)))} options={eligibleMeals(p, e.recipe.slot).map(m => [m.id, m.name])} />
          <details><summary>{t('Ingredients & preparation')}</summary><ul>{e.recipe.ingredients.map(ing => <li key={ing.foodId}>{Math.round(ing.grams * e.scale)} g {t(ing.food.name)} <a href={`https://fdc.nal.usda.gov/food-details/${ing.food.source.fdcId}/nutrients`} target="_blank" rel="noreferrer" aria-label={`USDA source for ${ing.food.name}`}>↗</a></li>)}</ul><p>{t(e.recipe.method)}</p><p className="small muted">{e.recipe.minutes} {t('min using prepared ingredients. Batch cooking time is additional.')}</p></details>
        </article>
      })}</div>
      <details className="card"><summary>{t('7-day grocery & preparation list')}</summary><p className="small muted">{t('These are edible quantities in the named state, not purchase weights. Cooked beans and rice weigh more than their dry ingredients. Use ready-cooked products or measure your own cooked batch yield; no misleading dry-weight conversion is applied.')}</p><ul>{groceryList(preview).map(row => <li key={row.foodId}>{row.grams} g {t(row.name)}</li>)}</ul></details>
      <ErrorNotice error={error} /><button className="btn primary" disabled={!preview.name.trim() || !!checkNutritionPlan(preview, p)} onClick={save}>{t('Save as a new meal plan')}</button>
    </> : <>
      <div className="planner-tabs"><button className={'btn ' + (mode === 'build' ? 'primary' : 'ghost')} onClick={() => setMode('build')}>{t('Build a menu')}</button><button className={'btn ' + (mode === 'saved' ? 'primary' : 'ghost')} onClick={() => setMode('saved')}>{t('Saved menus')} ({S.dietPlans?.length || 0})</button><button className={'btn ' + (mode === 'foods' ? 'primary' : 'ghost')} onClick={() => { setQuery(''); setMode('foods') }}>{t('Food library')}</button></div>
      {mode === 'build' && <form onSubmit={e => { e.preventDefault(); act(() => { setPreview(generateNutritionPlan(p, S.week)); setDayIndex(0) }) }}>
        <section className="card"><h2>{t('First, a quick safety check')}</h2><p>{t('Vegetarian/non-vegetarian and allergies are a start. Meal frequency, preparation time and exclusions make the menu usable; body measurements are only needed for estimated energy targets.')}</p><Check label="I am 18 or older" checked={p.adult} onChange={v => change('adult', v)} /><Check label="I am pregnant or breastfeeding, have eating-disorder concerns, or need a medical/therapeutic diet" checked={p.medical} onChange={v => change('medical', v)} /><p className="small muted">{t('This is general wellness guidance, not a treatment plan. Severe allergies require checking labels, restaurant preparation and cross-contact; a recipe filter cannot certify food as allergen-free.')}</p></section>
        <section className="card"><h2>{t('What you eat')}</h2><Select label="Dietary pattern" value={p.diet} onChange={v => change('diet', v)} options={DIETS} /><p className="small muted">{t('Vegetarian includes dairy but not eggs; eggetarian includes eggs and dairy. Non-vegetarian also allows plant-based meals. All catalog meat is chicken or fish; no certification of halal, kosher or other preparation standards is implied.')}</p><Choices label="Food allergies" values={p.allergens} options={ALLERGENS} onChange={v => change('allergens', v)} /><Choices label="Intolerances" values={p.intolerances} options={INTOLERANCES} onChange={v => change('intolerances', v)} /><Choices label="Cultural ingredient exclusions" values={p.cultural} options={CULTURAL} onChange={v => change('cultural', v)} />
          <Field label="Search ingredients to exclude (dislikes or additional restrictions)"><input className="input" value={query} onChange={e => setQuery(e.target.value)} /></Field>{query && shownFoods.slice(0, 15).map(f => <Check key={f.id} label={f.name} checked={p.excludedFoods.includes(f.id)} onChange={on => change('excludedFoods', on ? [...p.excludedFoods, f.id] : p.excludedFoods.filter(id => id !== f.id))} />)}{query && !shownFoods.length && <p role="status">{t('No matching ingredient. An unsupported allergy must be marked “other / uncertain”; do not assume a text search covers it.')}</p>}<div className="chips">{p.excludedFoods.map(id => <button className="chip" type="button" key={id} onClick={() => change('excludedFoods', p.excludedFoods.filter(x => x !== id))}>{FOODS.find(f => f.id === id)?.name || id} ×</button>)}</div>
        </section>
        <section className="card"><h2>{t('Make it fit your day')}</h2><div className="planner-grid"><Select label="Meals including snacks" value={p.meals} onChange={v => change('meals', v)} options={['3', '4', '5']} /><Select label="Preparation minutes per meal (batch cooking extra)" value={p.minutes} onChange={v => change('minutes', v)} options={['15', '30', '45']} /><Select label="Budget preference" value={p.budget} onChange={v => change('budget', v)} options={['low', 'standard']} /><Select label="Base portion size" value={p.portion} onChange={v => change('portion', v)} options={['smaller', 'regular', 'larger']} /><Select label="Goal" value={p.goal} onChange={v => change('goal', v)} options={GOALS} /></div><p className="small muted">{t('Budget is a relative ingredient preference, not a live price estimate. Portion sizes are shown in grams; household bowls and rotis vary too much to be exact.')}</p>
          <Check label="Personalize estimated energy targets (optional)" checked={p.targets} onChange={v => change('targets', v)} />{p.targets && <div className="planner-grid">{[['age', 'Age in years'], ['height', 'Height in cm'], ['weight', 'Weight in kg']].map(([key, label]) => <Field key={key} label={label}><input className="input" type="number" step="any" value={p[key]} onChange={e => change(key, e.target.value)} /></Field>)}<Select label="Physiological sex used by the energy equation" value={p.sex} onChange={v => change('sex', v)} options={[[ '', 'Choose, or switch off targets'], ['female', 'female'], ['male', 'male']]} /><Select label="Usual activity, including workouts" value={p.activity} onChange={v => change('activity', v)} options={['low', 'moderate', 'high']} /><p className="small muted">{t('Low: mostly seated with light activity. Moderate: regularly active. High: physically demanding days. Do not add workout calories again.')}</p></div>}
        </section>
        <section className="card"><Check label="I reviewed the exclusions above and understand the cross-contact limitations" checked={p.exclusionsConfirmed} onChange={v => change('exclusionsConfirmed', v)} /><p className="small muted">{t('Preferences stay on this device in guest mode. Signed-in profiles sync through the same account backup as workout data. Plan-sharing files never include these answers or meals.')}</p><div className="planner-tabs"><button type="submit" className="btn primary">{t('Build my 7-day preview')}</button><button type="button" className="btn" onClick={() => { update(s => saveNutritionPreferences(s, p)); notify('Preferences saved. Incompatible active menus have been deactivated.') }}>{t('Save preferences & check saved menus')}</button></div></section>
      </form>}
      {mode === 'saved' && <>
        {scheduleChanged && <p className="planner-notice">{t('Your workout schedule changed after this menu was created. Generate a new preview to refresh workout-day swaps; your saved meals have not been silently changed.')}</p>}
        {activeDiet?.activatedAt && Date.now() - (activeDiet.reviewedAt || activeDiet.activatedAt) >= 56 * 86400000 && <div className="planner-notice"><p>{t('Eight-week menu check-in: review appetite, food preferences and recovery. Refresh your estimates if your circumstances changed.')}</p><button className="btn" onClick={() => update(s => { s.dietPlans.find(d => d.id === activeDiet.id).reviewedAt = Date.now() })}>{t('Mark reviewed')}</button></div>}
        {!S.dietPlans?.length && <div className="empty">{t('No saved menus yet. Build a preview first.')}</div>}
        <div className="planner-grid">{S.dietPlans?.map(plan => { const issue = checkNutritionPlan(plan, p); return <article className="card" key={plan.id}><Field label="Menu name"><input className="input" value={plan.name} maxLength={100} onChange={e => update(s => { s.dietPlans.find(x => x.id === plan.id).name = e.target.value })} /></Field>{S.activeDietPlanId === plan.id && <span className="tag acc">{t('Active menu')}</span>}<p className="small muted">{plan.profileSnapshot.diet} · {plan.profileSnapshot.meals} {t('meals per day')}</p><ErrorNotice error={issue} /><div className="planner-tabs"><button className="btn" onClick={() => { setPreview(clone(plan)); setDayIndex(0) }}>{t('View / swap')}</button><button className="btn primary" disabled={!!issue || S.activeDietPlanId === plan.id} onClick={() => activate(plan.id)}>{t('Activate')}</button><button className="btn ghost" onClick={() => update(s => { s.dietPlans.push({ ...clone(plan), id: uid(), name: plan.name + ' (copy)', createdAt: Date.now(), activatedAt: null }) })}>{t('Duplicate')}</button><button className="btn ghost danger" onClick={() => { if (window.confirm(t('Delete this saved menu? This cannot be undone.'))) update(s => { s.dietPlans = s.dietPlans.filter(x => x.id !== plan.id); if (s.activeDietPlanId === plan.id) s.activeDietPlanId = null }) }}>{t('Delete')}</button></div></article> })}</div>
      </>}
      {mode === 'foods' && <><Field label="Search the food library"><input className="input" value={query} onChange={e => setQuery(e.target.value)} /></Field><p className="small muted">{FOODS.length} {t('ingredients. All values are per 100 g edible portion in the named raw/cooked state. Generic foods differ from brands and Indian varieties. Check product labels.')}</p><div className="planner-grid">{shownFoods.map(f => <article className="card food-card" key={f.id}><h3>{t(f.name)}</h3><p className="small">{f.kcal} kcal · {f.protein} g {t('protein')} · {f.diet}</p><p className="small muted">{t('Ingredient allergens')}: {f.allergens.join(', ') || t('none tagged; cross-contact unknown')}</p><a href={`https://fdc.nal.usda.gov/food-details/${f.source.fdcId}/nutrients`} target="_blank" rel="noreferrer">USDA #{f.source.fdcId}</a></article>)}</div></>}
    </>}
    <section className="planner-source small muted"><p>{t('Nutrition estimates use USDA SR Legacy 2018 ingredient data. Recipes are authored combinations, not laboratory-tested Indian dishes. Menus are general guidance and are not dietitian-approved or nutritionally complete prescriptions.')}</p><p>{t('Use fully cooked pulses, meat and eggs, safe water and appropriate refrigeration. Batch-cooking times are not included in quick-meal estimates.')}</p><a href="https://www.nin.res.in/dietaryguidelines/pdfjs/locale/DGI07052024P.pdf" target="_blank" rel="noreferrer">ICMR–NIN dietary guidance</a> · <a href="https://fdc.nal.usda.gov/download-datasets/" target="_blank" rel="noreferrer">USDA data (CC0)</a> · <a href="https://pubmed.ncbi.nlm.nih.gov/2305711/" target="_blank" rel="noreferrer">Energy equation</a> · <a href="https://www.foodsafety.gov/food-safety-charts/safe-minimum-internal-temperatures" target="_blank" rel="noreferrer">Food safety</a> · <a href="https://github.com/arnayshukla/openGym/issues/new" target="_blank" rel="noreferrer">{t('Report content')}</a></section>
  </div>
}
